<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find ackermann_vehicle_description)/urdf/common_properties.xacro" />

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"
                                    o_xyz="0 0 0" o_rpy="${pi/2} 0 0"/>
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="ackermann_robot" params="robot_parameters_file">
        <xacro:get_model_parameters file="${robot_parameters_file}" />

        <link name="base_footprint"/>

        <link name="base_link">
            <xacro:box_inertia m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}" o_xyz="0 0 ${base_height/2}" o_rpy="0 0 0"/>
            <visual>
                <origin xyz="0.0 0.0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <material name="green"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
            </collision>
        </link>
        

    </xacro:macro>
</robot>