<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Gazebo Parameters -->
  <gazebo reference="body_link">
    <mu1>0.0001</mu1>
    <mu2>0.0001</mu2>
  </gazebo>

  <gazebo reference="front_right_wheel_link">
    <mu1>10.0</mu1>
    <mu2>10.0</mu2>
  </gazebo>

  <gazebo reference="front_left_wheel_link">
    <mu1>10.0</mu1>
    <mu2>10.0</mu2>
  </gazebo>
    
  <gazebo reference="rear_right_wheel_link">
    <mu1>10.0</mu1>
    <mu2>10.0</mu2>
  </gazebo>

  <gazebo reference="rear_left_wheel_link">
    <mu1>10.0</mu1>
    <mu2>10.0</mu2>
  </gazebo>

  <!-- Gazebo Plugins -->

  <gazebo>
    <plugin name='gz::sim::systems::AckermannSteering' filename='gz-sim-ackermann-steering-system'>
        <left_joint>rear_left_wheel_joint</left_joint>
        <right_joint>rear_right_wheel_joint</right_joint>
        <left_steering_joint>front_left_steering_joint</left_steering_joint>
        <right_steering_joint>front_right_steering_joint</right_steering_joint>
        <kingpin_width>${wheel_separation}*0.8</kingpin_width>
        <steering_limit>${max_steering_angle}</steering_limit>
        <wheel_base>${wheel_offset*2.0}</wheel_base>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_radius>${wheel_radius}</wheel_radius>
        <min_velocity>-${max_velocity}</min_velocity>
        <max_velocity>${max_velocity}</max_velocity>
        <min_acceleration>-30</min_acceleration>
        <max_acceleration>30</max_acceleration>

        <topic>cmd_vel</topic>
        <frame_id>odom</frame_id>
        <child_frame_id>base_footprint</child_frame_id>
        <odom_publish_frequency>50</odom_publish_frequency>
    </plugin>
  </gazebo>
  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
      <topic>joint_states</topic>
      <joint_name>front_left_steering_joint</joint_name>
      <joint_name>front_right_steering_joint</joint_name>
      <joint_name>front_left_wheel_joint</joint_name>
      <joint_name>front_right_wheel_joint</joint_name>
      <joint_name>rear_left_wheel_joint</joint_name>
      <joint_name>rear_right_wheel_joint</joint_name>
    </plugin>
  </gazebo>
    
</robot>