<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_radius" value="0.05" />
    <xacro:property name="lidar_length" value="0.05" />

    <link name="lidar_link">
        <xacro:cylinder_inertia m="0.05" r="${lidar_radius}" l="${lidar_length}" 
                                o_xyz="0.0 0.0 ${lidar_length/2}" o_rpy="0.0 0.0 0.0"/>
        <visual>
            <origin xyz="0.0 0.0 ${lidar_length/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${lidar_length/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
        </collision>
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.0 0.0 ${base_height}" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <gazebo reference="lidar_link">
        <sensor name="lidar" type="gpu_lidar">
            <always_on>1</always_on>
            <update_rate>15</update_rate>
            <visualize>true</visualize>
            <topic>/scan</topic>
            <gz_frame_id>lidar_link</gz_frame_id>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.1416</min_angle>
                        <max_angle>3.1416</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>20.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </lidar>
        <!-- Sensor |camera,ray,imu,magnetometer,gps,force_torque,contact,sonar,rfidtag,rfid| -->
            <!-- <plugin name="gz::sim::systems::Sensors" filename="gz-sim-sensors-system">
                <render_engine>ogre2</render_engine>
            </plugin> -->
        </sensor>
        
    </gazebo>
    
</robot>