/**:
  ros__parameters:
    # Body params
    body_length: 0.425 # Length of the vehicle's body [m]
    body_width: 0.192 # Width of the vehicle's body [m]
    body_height: 0.182 # Height of the vehicle's body [m]
    body_mass: 2.552 # Mass of the vehicle's body [kg]
    wheel_base: 0.265 # Distance between front and rear axles [m]
    track_width: 0.167 # Distance between left and right wheels [m]

    # Wheel params
    wheel_radius: 0.0265 # Radius of each wheel [m]
    wheel_width: 0.025 # Width of each wheel [m]
    wheel_mass: 0.035 # Mass of the wheel material [kg]

    # Kinematics and dynamics params
    max_steering_angle: 0.3 # Maximum steering angle of the vehicle [rad]
    max_steering_angular_velocity: 1.570796 # Maximum steering angular velocity [rad/s]
    max_steering_effort: 1.0 # Maximum steering torque [Nm]
    max_velocity: 2.448696 # Maximum wheel velocity [m/s]
    max_effort: 5.12766 # Maximum wheel torque [Nm]